site_name: Predicción de Abandono Escolar - TFM
site_description: Documentación oficial del pipeline de datos y modelos.

theme:
  name: material
  features:
    - navigation.tabs # Menú superior horizontal
    - navigation.top  # Botón de "volver arriba"
    - search.suggest  # Autocompletar en la búsqueda
  palette:
    # Botón para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    # Botón para modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.] # le dice a MkDocs que busque la carpeta 'src' aquí

nav:
  - Inicio: index.md
  - Arquitectura: arquitectura.md
  - Referencia del Código:
    - Base de Datos: referencia/base_datos.md
    - Logs y Trazabilidad: referencia/logs.md
    - Analizador de datos: referencia/analizador_datos.md
    - Preparador de datos: referencia/preparador_datos.md
    - Visualizador de datos: referencia/visualizador.md
    - Evaluador de riesgo: referencia/evaluador_riesgo.md
    - Ingestor de datos: referencia/ingestor_datos.md
    - Orquestador: referencia/orquestador.md